# Generated by Django 2.1.7 on 2019-12-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HangmanCountry',
            new_name='Country',
        ),
    ]
